feat: add upgrade kubesphere cmd
kubesphere/kubekey pull request #1441
Opened 2022-08-14 10:44 UTC by 77yu77

### What type of PR is this?

/kind feature

### What this PR does / why we need it:

### Which issue(s) this PR fixes:

Fixes #1440 

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

```release-note
It provide user to use  "upgrade phase kubesphere " to upgrade worker nodes  as one step of the upgrade phase run.
```

### Additional documentation, usage docs, etc.:

```docs
Usage:
  kk upgrade phase kubesphere [flags]

Flags:
      --debug                    Print detailed information
      --download-cmd string      The user defined command to download the necessary binary files. The first param '%s' is output path, the second param '%s', is the URL (default "curl -L -o %s %s")
  -f, --filename string          Path to a configuration file
  -h, --help                     help for kubesphere
      --ignore-err               Ignore the error message, remove the host which reported error and force to continue
      --in-cluster               Running inside the cluster
      --namespace string         KubeKey namespace to use (default "kubekey-system")
      --with-kubernetes string   Specify a supported version of kubernetes
      --with-kubesphere          Deploy a specific version of kubesphere (default v3.3.0)
```

2022-08-14 10:44 UTC, 77yu77 commented
/assign @24sama

2022-08-15 16:14 UTC, 77yu77 commented
> pkg/alpha/nodes/modules.go don't need changed.

ok,I have delete it.

2022-08-15 16:15 UTC, 77yu77 commented
![image](https://user-images.githubusercontent.com/73932296/184673456-a41eaba9-8c28-457a-85b8-94ff9bbb3f6a.png)

2022-08-19 02:26 UTC, 24sama commented on cmd/ctl/alpha/kubesphere.go
> +	cmd.Flags().StringVarP(&o.DownloadCmd, "download-cmd", "", "curl -L -o %s %s",
I guess this flag is useless and can be removed.

2022-08-19 02:26 UTC, 24sama commented on pkg/alpha/precheck/task.go
> +	g.KubeConf.Cluster.Kubernetes.Version = apiserverVersion
Could you please tell me why need to assign a new value to this `g.KubeConf.Cluster.Kubernetes.Version`?

2022-08-19 02:26 UTC, 24sama commented on pkg/alpha/precheck/modules.go
> +	getKubernetesNodesStatus := &task.RemoteTask{
I think we don't need this module.

2022-08-19 08:16 UTC, 77yu77 commented
![image](https://user-images.githubusercontent.com/73932296/185575115-c00c177d-96be-4a55-833d-b89a93e46273.png)
I rewrite the confirm modules, so now it no need to get the cluster status and  KubeConf.Cluster.Kubernetes.Version.

2022-08-22 01:33 UTC, 24sama requested changes

2022-08-22 01:33 UTC, 24sama commented on pkg/alpha/confirm/task.go
> +		fmt.Printf("Continue upgrading cluster? [yes/no]: ")
Continue upgrading cluster? -> Continue upgrading KubeSphere?

2022-08-22 07:55 UTC, 24sama commented
/lgtm
/approve

2022-08-22 07:56 UTC, merged